services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        POSTGRES_USERNAME: $POSTGRES_USERNAME
        POSTGRES_DATABASE: $POSTGRES_DATABASE
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_HOST: $POSTGRES_HOST

    volumes:
      - .:/opt/app

    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./postgres-data:/var/lib/posgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
